name: Python CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

# -----------------------------
# 1. TEST BEFORE DEPLOYMENT
# -----------------------------
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --cov=app --cov-report=term-missing

# -----------------------------
# 2. BUILD PACKAGE
# -----------------------------
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

# -----------------------------
# 3. DEPLOY + TEST ON LINUX
# -----------------------------
  deploy-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install package
      run: |
        pip install dist/*.whl

    - name: Smoke Test
      run: |
        python -c "from app.sentiment import analyze_sentiment; print(analyze_sentiment('good'))"

    - name: Run tests again (System + Regression)
      run: |
        pytest
